### ISSUE TITLE
Cannot read property 'program' of undefined

### ISSUE THREAD

**Issue by csprocket777** [ember-learn/ember-cli-addon-docs-esdoc#36]
I'm trying to replicate what I see in your repo to generate my docs and am running into an error:

```
Cannot read property 'program' of undefined
```

Here's the error output:
```
=================================================================================

ENV Summary:

  TIME: Tue Nov 16 2021 17:34:39 GMT-0600 (Central Standard Time)
  TITLE: ember
  ARGV:
  - /Users/[user_directory]/.nvm/versions/node/v14.17.3/bin/node
  - /usr/local/bin/ember
  - s
  EXEC_PATH: /Users/[user_directory]/.nvm/versions/node/v14.17.3/bin/node
  TMPDIR: /var/folders/_8/c8x5jpjn3m128c2k47kwrr8h0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/[user_directory]/.nvm/versions/node/v14.17.3/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/go/bin
  - /Applications/Little Snitch.app/Contents/Components
  - /usr/local/share/dotnet
  - ~/.dotnet/tools
  - /Library/Apple/usr/bin
  - /Library/Frameworks/Mono.framework/Versions/Current/Commands
  PLATFORM: darwin x64
  FREEMEM: 48439296
  TOTALMEM: 17179869184
  UPTIME: 28382
  LOADAVG: 30.48291015625,13.52099609375,9.55078125
  CPUS:
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.17.1
  - brotli: 1.0.9
  - cldr: 39.0
  - icu: 69.1
  - llhttp: 2.1.3
  - modules: 83
  - napi: 8
  - nghttp2: 1.42.0
  - node: 14.17.3
  - openssl: 1.1.1k
  - tz: 2021a
  - unicode: 13.0
  - uv: 1.41.0
  - v8: 8.4.371.23-node.67
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property 'program' of undefined
    at DocFactory._inspectExportDefaultDeclaration (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/Factory/DocFactory.js:135:40)
    at new DocFactory (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/Factory/DocFactory.js:90:10)
    at Function._traverse (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:233:21)
    at /Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:112:25
    at Function._walk (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:204:9)
    at Function._walk (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:206:14)
    at Function._walk (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:206:14)
    at Function._walk (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:206:14)
    at Function.generate (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:96:10)
    at generateESDoc (/Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli-addon-docs-esdoc/lib/preprocessors/generate-esdoc.js:53:11)
  - code: [undefined]
  - codeFrame: Cannot read property 'program' of undefined
  - errorMessage: Cannot read property 'program' of undefined
        at DocsGenerator
-~- created here: -~-
    at DocsGenerator.Plugin (/Users/[user_directory]/Documents/[project_directory]/node_modules/broccoli-plugin/index.js:7:31)
    at new CachingWriter (/Users/[user_directory]/Documents/[project_directory]/node_modules/broccoli-caching-writer/index.js:18:10)
    at new DocsGenerator (/Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli-addon-docs-esdoc/lib/broccoli/generator.js:16:5)
    at Class.createDocsGenerator (/Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli-addon-docs-esdoc/index.js:11:12)
    at /Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli-addon-docs/lib/models/plugin-registry.js:32:11
    at Array.map (<anonymous>)
    at PluginRegistry.createDocsGenerators (/Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli-addon-docs/lib/models/plugin-registry.js:31:43)
    at Class.postprocessTree (/Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli-addon-docs/index.js:302:43)
    at /Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Cannot read property 'program' of undefined
        at DocsGenerator
-~- created here: -~-
    at DocsGenerator.Plugin (/Users/[user_directory]/Documents/[project_directory]/node_modules/broccoli-plugin/index.js:7:31)
    at new CachingWriter (/Users/[user_directory]/Documents/[project_directory]/node_modules/broccoli-caching-writer/index.js:18:10)
    at new DocsGenerator (/Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli-addon-docs-esdoc/lib/broccoli/generator.js:16:5)
    at Class.createDocsGenerator (/Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli-addon-docs-esdoc/index.js:11:12)
    at /Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli-addon-docs/lib/models/plugin-registry.js:32:11
    at Array.map (<anonymous>)
    at PluginRegistry.createDocsGenerators (/Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli-addon-docs/lib/models/plugin-registry.js:31:43)
    at Class.postprocessTree (/Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli-addon-docs/index.js:302:43)
    at /Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: DocsGenerator
  - originalErrorMessage: Cannot read property 'program' of undefined
  - stack: TypeError: Cannot read property 'program' of undefined
    at DocFactory._inspectExportDefaultDeclaration (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/Factory/DocFactory.js:135:40)
    at new DocFactory (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/Factory/DocFactory.js:90:10)
    at Function._traverse (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:233:21)
    at /Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:112:25
    at Function._walk (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:204:9)
    at Function._walk (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:206:14)
    at Function._walk (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:206:14)
    at Function._walk (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:206:14)
    at Function.generate (/Users/[user_directory]/Documents/[project_directory]/node_modules/esdoc/out/src/ESDoc.js:96:10)
    at generateESDoc (/Users/[user_directory]/Documents/[project_directory]/node_modules/ember-cli-addon-docs-esdoc/lib/preprocessors/generate-esdoc.js:53:11)

=================================================================================
```

**Comment by csprocket777** [comment]
For anyone else (future self included) running into this issue, here's how I resolved it:
- I put a conditional breakpoint in the `constructor` function of the `DocFactory.js` class in the `esdoc` node_module looking for `ast === undefined` (`node_modules/esdoc/out/src/Factory/DocFactory.js`)
- Then I inspected the filepath it was having troubles with
- Turns out that it was having troubles with `??` and `?.` usages in my code. Once I changed those over to more verbose forms, it compiled and I now have working documentation derived from my Typescript based code.
